backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "players" # Used in routes, e.g., /admin/collections/blog
    label: "Players" # Used in the UI
    folder: "src/routes/rosters" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Gamer Tag", name: "gamerTag", widget: "string", required: true, hint: "Enter your gamer tag."}
      - {label: "IRL Name", name: "IRL", widget: "string"}
      - {label: "Player Picture", name: "playerPicture", widget: "image", hint: "Upload a profile picture."}
      - {label: "Social Media Links", name: "socialMedia", widget: "list", required: false, field: 
          {
            label: "Social Media",
            name: "socialMedia",
            widget: "object",
            fields:
              [
                {
                  label: "Platform",
                  name: "platform",
                  widget: "select",
                  options: ["Twitter", "Facebook", "Instagram", "YouTube", "Twitch", "Discord", "Other"],
                  default: "Other",
                  hint: "Select the social media platform."
                },
                {
                  label: "URL",
                  name: "url",
                  widget: "string",
                  pattern: ['^(http|https)://', 'Must be a valid URL'],
                  hint: "Enter the full URL to the profile."
                }
              ]
          },
        hint: "Add the player's social media profiles."
        }
      - {label: "About Player", name: "about", widget: "text", hint: "Write a short bio about the player."}
      - {label: "Esports Team & Role", name: "esportsTeamAndRole", widget: "object", required: true, fields: 
          [
            {label: "Esports Team", name: "esportsTeam", widget: "relation", collection: "Teams", search_fields: ["teamName"], display_fields: ["teamName"], value_field: "teamName", hint: "Select the professional Esports team."},
            {label: "Team Roles", name: "teamRoles", widget: "list", field: {label: "Role", name: "role", widget: "string", hint: "Add roles as applicable."}}
          ]
        }
      - {label: "Role In Org", name: "roleInOrg", widget: "list", field: {label: "Role", name: "role", widget: "string"}}
      - {label: "Computer Specs", name: "computerSpecs", widget: "object", fields: [{label: "CPU", name: "cpu", widget: "string"}, {label: "GPU", name: "gpu", widget: "string"}, {label: "RAM", name: "ram", widget: "string"}]}
      - {label: "Clips", name: "clips", widget: "list", field: {label: "Clip", name: "clip", widget: "file", hint: "Upload a video clip or provide a URL."}}
      - {label: "Ranks", name: "ranks", widget: "list", fields: [{label: "Game Name", name: "gameName", widget: "string"}, {label: "Game Rank", name: "gameRank", widget: "string"}]}
      - {label: "Player Achievements", name: "playerAchievements", widget: "list", field: {label: "Achievement", name: "achievement", widget: "string"}}
      - {label: "Favorite Games", name: "favoriteGames", widget: "list", field: {label: "Game", name: "game", widget: "string"}}
      - {label: "Recent Game", name: "recentGame", widget: "string", hint: "Add a game you've played recently."}
  - name: "blogs"
    label: "Blogs"
    folder: "src/routes/blog"
    create: true
    slug: "{{day}}-{{month}}-{{year}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Author", name: "author", widget: "relation", required: true, collection: "players", search_fields: ["gamerTag", "IRL"], searchFields: ["gamerTag", "IRL"], display_fields: ["gamerTag", "IRL"], value_field: "gamerTag", valueFields: "gamerTag"}
      - {label: "Content", name: "body", widget: "markdown", required: true, }
      - {label: "Short Summary", name: 'summary', widget: 'markdown', required: true}
  - name: "Teams"
    label: "Teams"
    folder: "src/routes/roster"
    create: true
    slug: "{{day}}-{{month}}-{{year}}"
    fields:
      - {label: "Team Name", name: "teamName", widget: "string", required: true, hint: "Enter the official Esports team name."}
      - {label: "Game", name: "game", widget: "string", required: true, hint: "Enter the game the team competes in, e.g., League of Legends, Valorant."}
      - {label: "Team Picture", name: "teamPicture", widget: "image", required: false, hint: "Upload the team's logo or a group picture."}
      - {label: "Teammates", name: "teammates", widget: "list", required: true, field: 
          {label: "Player", name: "player", widget: "relation", collection: "players", search_fields: ["gamerTag", "IRL"], display_fields: ["gamerTag"], value_field: "gamerTag", hint: "Select players that are part of this team."}
        }
      - {label: "Team Achievements", name: "teamAchievements", widget: "list", required: false, field: {label: "Achievement", name: "achievement", widget: "string", hint: "List significant achievements of the team."}}
      - {label: "Social Media Links", name: "socialMedia", widget: "list", required: false, field: 
          {
            label: "Social Media",
            name: "socialMedia",
            widget: "object",
            fields:
              [
                {
                  label: "Platform",
                  name: "platform",
                  widget: "select",
                  options: ["Twitter", "Facebook", "Instagram", "YouTube", "Twitch", "Discord", "Other"],
                  default: "Other",
                  hint: "Select the social media platform."
                },
                {
                  label: "URL",
                  name: "url",
                  widget: "string",
                  pattern: ['^(http|https)://', 'Must be a valid URL'],
                  hint: "Enter the full URL to the profile."
                }
              ]
          },
        hint: "Add the team's social media profiles."
        }
      - {label: "About Team", name: "aboutTeam", widget: "markdown", required: false, hint: "Write a detailed description about the team, its history, strategy, and goals."}
      - {label: "Recent Matches", name: "recentMatches", widget: "list", required: false, fields: 
          [
            {label: "Opponent Team", name: "opponentTeam", widget: "string"},
            {label: "Result", name: "result", widget: "string"},
            {label: "Date", name: "date", widget: "datetime"}
          ], hint: "Add recent match details like opponent, result, and date."
        }
      - {label: "Team Rank", name: "teamRank", widget: "string", required: false, hint: "Enter the team's current ranking in their respective league or competition. Leave blank if not applicable."}
      - {label: "Team Clips", name: "teamClips", widget: "list", required: false, hint: "Add clips that showcase the team's highlights or important moments.", fields:
          {
            label: "Clip Title",
            name: "title",
            widget: "string",
            required: true,
            hint: "Enter a descriptive title for the clip."
          }
          {
            label: "Clip URL",
            name: "url",
            widget: "string",
            required: false,
            pattern: ['^(http|https)://', 'Must be a valid URL'],
            hint: "Enter the URL where the clip can be found (e.g., YouTube or Twitch)."
          }
          {
            label: "Upload Clip",
            name: "file",
            widget: "file",
            required: false,
            hint: "Alternatively, upload a video file for the clip. Acceptable formats are .mp4, .webm, etc."
          }}
  # - name: "news"